<?php

namespace Wbi\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnderdomainRepository extends EntityRepository
{
}
